version: "3"

services:
  nginx:
    container_name: wednesday_nginx
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    working_dir: /var/www
    ports:
      - "8080:80"
  php-fpm:
#    image: wednesday_php-fpm
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    working_dir: /var/www
    tty: true
    restart: unless-stopped
    volumes:
      - ./:/var/www
  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=app"
      - "MYSQL_USER=app"
      - "MYSQL_PASSWORD=app"
      - "MYSQL_DATABASE=wednesday"
    ports:
      - "3306:3306"
#  redis:
#    container_name: wednesday_redis
#    image: redis:latest
#    restart: unless-stopped
#    ports:
#      - "6379:6379"

volumes:
  mysql:
    driver: local
